### ISSUE TITLE
Some error occurred (click for details) since 1.7 or 1.7.1

### ISSUE THREAD

**Issue by LiloBzH** [maxpozdeev/mytinytodo#44]
Hi

I tried to upgrade to 1.7 and it doesnt work mais i dont know why.
No real mistake.

In details page => HTML code mais it seems to be ok.

How to debug to find issue ?

NGINX / PHP 8.1

**Comment by maxpozdeev** [comment]
Your error (Some error occurred) seems because your database requires upgrade to v1.7.
This can be done in setup.php but update process is broken...
Stupid mistake in setup made while line formatting and not fully tested.

Fixed. You can update setup.php by downloading updated one at https://github.com/maxpozdeev/mytinytodo/raw/master/src/setup.php

**Comment by maxpozdeev** [comment]
Changed title, original: Some error occurred (click for details) since 1.7 or 1.7.1

**Comment by LiloBzH** [comment]
no i m sorry, a open 1 ticket for 2 bugs ^^

i will open new ticket
